[package]
name = "alphanet-precompile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
revm-precompile.workspace = true
revm-primitives.workspace = true

bls12_381 = "0.8.0"
p256 = { version = "0.13.2", features = ["ecdsa"] }

[dev-dependencies]
eyre.workspace = true
rstest.workspace = true
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.115"

[lints]
workspace = true
